version: '3.6'

services:

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - 9090:80 # change to 80:80 when the shop is ready to go live
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
      # Add all the custom folders
      - ./custom/themes/netar-storefront:/var/www/html/wp-content/themes/netar-storefront
      - ./custom/plugins/netar-blocks:/var/www/html/wp-content/plugins/netar-blocks
  db:
    image: mysql:5.7
    volumes:
      - ./database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 9091:80
